### ISSUE TITLE
Bug for special `key` 

### ISSUE THREAD

**Issue by Milittle** [rustbase/dustdata#23]
As a titile, I notice if I delete `key` twice, every time key exist in storage engine.

![图片](https://user-images.githubusercontent.com/9550695/219952020-77ba75a2-c261-4cf7-90f5-39166a836614.png)

I put the print message in dustdata:

![图片](https://user-images.githubusercontent.com/9550695/219952120-88d45e50-0090-4d13-bde3-358a872ec3cc.png)

But for other key: such as `key1`, it will be raise the Key does not exist. strange problem.

![图片](https://user-images.githubusercontent.com/9550695/219952207-c1d8702d-bc26-450f-ab9e-343a493bc0e7.png)

**Comment by peeeuzin** [comment]
Are you inserted `key` before? DustData flush all the data in disk when:
 - DustData struct is flush from memory;
 - Call `flush` function on DustData;
 - Memtable size or more than `flush_threshold`;

**Comment by Milittle** [comment]
> 

Yes, but other key can delete by delete interface, only `key` have some problem

**Comment by Milittle** [comment]
> > 
> 
> Yes, but other key can delete by delete interface, only key have some problem

If key be deleted, the bloom filter do not udpate the filter directory meta files?

**Comment by peeeuzin** [comment]
The bug is related with Dense Index, it's seems that DustData is not deleting keys flushed to disk.
